pila-estatica: pila_estatica.c
	clear
	gcc -w pila_estatica.c -o pila_estatica
	./pila_estatica
	rm -f ./pila_estatica
pila-dinamica: pila_dinamica.c
	clear
	gcc pila_dinamica.c -o pila_dinamica
	./pila_dinamica
	rm -f ./pila_dinamica
cola-dinamica: cola_dinamica.c
	clear
	gcc cola_dinamica.c -o cola_dinamica
	./cola_dinamica
	rm -f ./cola_dinamica
